# Generated by Django 2.0 on 2018-02-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=36, unique=True)),
                ('tmdb_id', models.IntegerField()),
                ('seen', models.NullBooleanField()),
            ],
            options={
                'verbose_name_plural': 'watchlist',
                'ordering': ('tmdb_id',),
            },
        ),
    ]
